version: '3'
services:

  mysql:
    image: mardixx/vple-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: VPLE

  frontend:
    image: mardixx/vple-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    container_name: frontend
    ports:
      - "3000:3000"

  backend:
    image: mardixx/vple-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/VPLE?characterEncoding=UTF-8
    container_name: backend

  nginx:
    restart: always
    image: mardixx/vple-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
